### ISSUE TITLE
Can you please share your career journey with us?

### ISSUE THREAD

**Issue by anku255** [ananyaneogi/ama#2]
Hi Ananya! 

I am interested in your career journey so far. How did you end up getting a front end developer job at Parallel Labs? When and how did you get started with frontend development? Do you have a Computer Science background? 

Thanks.

**Comment by ananyaneogi** [comment]
Hi! 
I have a degree in computer science so I was involved in programming throughout the coursework. However I got started on frontend only towards the end of my college. Once I started learning frontend on my own I was hooked and knew this is what I wanted to work on. Unfortunately I did not have any internship experience specific to frontend by that time so I started making small projects of my own and built a portfolio site to showcase all my projects. At that time I also wanted to learn design and work on a lot of different projects so I chose to apply to a bunch of digital design companies. I applied to a lot such companies but only got call from 2-3, one of them was Parallel Labs and I ended up working there.

Even though I did study CS in my university but most of what I do now is self taught through books and the internet. The learning never stops :)

**Comment by anku255** [comment]
Thanks for the answer.

I am a final year CSE student myself. I started with android development but got hooked into web development when I first tried it 2 years ago. I do MERN stack currently.

I am surprised that you went for web design initially because I believed that it requires a lot of practice (and something I not good at 😄). How did you learn design? How much time did it take before you started coming up with your own design?

**Comment by ananyaneogi** [comment]
It was all self learning through articles and books. I also took classes on [Skillshare](https://skl.sh/2NWIGhN) for learning tools such as sketch, illustrator etc and it was a big help. 
I think there is no particular timeframe where you just start coming up with your own designs, it's part of entire the process. The more you practise the better you become.
